#ifndef ONTOLISAVISNODECOLOR_GLOBAL_H
#define ONTOLISAVISNODECOLOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONTOLISAVISNODECOLOR_LIBRARY)
#  define ONTOLISAVISNODECOLORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONTOLISAVISNODECOLORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONTOLISAVISNODECOLOR_GLOBAL_H
