#ifndef ONTOLISAVISNODEROUNDEDRECT_GLOBAL_H
#define ONTOLISAVISNODEROUNDEDRECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONTOLISAVISNODEROUNDEDRECT_LIBRARY)
#  define ONTOLISAVISNODEROUNDEDRECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONTOLISAVISNODEROUNDEDRECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONTOLISAVISNODEROUNDEDRECT_GLOBAL_H
