#ifndef ONTOLISAVISNODEEXPANDSTATUS_GLOBAL_H
#define ONTOLISAVISNODEEXPANDSTATUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONTOLISAVISNODEEXPANDSTATUS_LIBRARY)
#  define ONTOLISAVISNODEEXPANDSTATUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONTOLISAVISNODEEXPANDSTATUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONTOLISAVISNODEEXPANDSTATUS_GLOBAL_H
