#ifndef OLSADAPTIVENODETEXTAREAVISUALIZER_GLOBAL_H
#define OLSADAPTIVENODETEXTAREAVISUALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OLSADAPTIVENODETEXTAREAVISUALIZER_LIBRARY)
#  define OLSADAPTIVENODETEXTAREAVISUALIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OLSADAPTIVENODETEXTAREAVISUALIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OLSADAPTIVENODETEXTAREAVISUALIZER_GLOBAL_H
