#ifndef ONTOLISAVISNODEELLIPSE_GLOBAL_H
#define ONTOLISAVISNODEELLIPSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONTOLISAVISNODEELLIPSE_LIBRARY)
#  define ONTOLISAVISNODEELLIPSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONTOLISAVISNODEELLIPSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONTOLISAVISNODEELLIPSE_GLOBAL_H
